### ISSUE TITLE
Renaming ZipkinUrl option into httpReporterUrl

### ISSUE THREAD

**Issue by jcchavezs** [fastify/fastify-zipkin#3]
## 🚀 Feature Proposal

Consider renaming `ZipkinUrl` into `httpReporterUrl`. Since this is a zipkin repository, it feels redundant.

**Comment by mcollina** [comment]
Would you mind to send a PR keeping the old option as an alias?

**Comment by Eomm** [comment]
We don't have release this module right now (I forgot to warn @mcollina  - I don't have right to release the first version), so it would not be a breaking change 😅
