### ISSUE TITLE
JSON parsing loses zipkin context

### ISSUE THREAD

**Issue by kedarv** [fastify/fastify-zipkin#46]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

n/a

### Node.js version

14.17.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18.04

### Description

Note: I'm using a different logger, which is why I put in `n/a` for the Plugin version -- I've essentially forked it and only replaced the first couple lines (using explicit context instead of CLS Context, and a different logger instead of HttpLogger).

I noticed that using this zipkin hook works pretty well, except for POST routes with JSON. For whatever reason, I wasn't able to log [locals](https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin#local-tracing) `tracer.local()`. I did some digging by removing all content parsers, and verified that my local trace showed up, which made me suspect that somehow parsing was messing up the zipkin context.

I tried changing the hook to run after parsing:
```
app.addHook('preValidation', (req, res, done) => {
        tracer.scoped(() => {
            const id = instrumentation.recordRequest(
...
```

and observed that my local trace was working again. Interestingly, in the [zipkin-context-cls library](https://www.npmjs.com/package/zipkin-context-cls#troubleshooting), it is mentioned that:
>the body-parser middleware may interfere and lose the context. To prevent that, make sure that the body-parser middleware is registered before zipkin in the middleware chain. If you are not explicitly registering body-parser, please do so by adding app.use(bodyParser.json()); above the Zipkin middleware registration line.

I believe a similar issue is present in this library.

### Steps to Reproduce

```javascript
    const app = fastify();
    const tracer = new Tracer(...)
    const instrumentation = new Instrumentation.HttpServer({ tracer, port: 0 });

    // onRequest will result in the tracer.local call not being recorded in the response. Must be preValidation
    app.addHook('onRequest', (req, res, done) => {
        tracer.scoped(() => {
            const id = instrumentation.recordRequest(
                req.raw.method,
                url.format(req.raw.url),
                readHeader.bind(req.headers)
            )
            res._zipkinId = id
            req.requestContext.set('zipkinTraceId', id); // using fastify-request-context to store the tracer
            done()
        })
    });

  app.post('/endpoint', async (request, reply) => {
        // it will not work when hooked to onRequest
        tracer.local('do you work?', () => { });
        tracer.scoped(() => {
            instrumentation.recordResponse(request.requestContext.get('zipkinTraceId'), 200)
            console.log(tracer.id);
        });
        reply.code(200).send('test');
    });
```

### Expected Behavior

Expected behavior is that the context is maintained, even when using content type parsers: https://github.com/fastify/fastify/blob/7c1bcd176c6a1aaeef3d07f5c079c2d503013f08/lib/handleRequest.js

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by kedarv** [comment]
Unfortunately, I don't have bandwidth right now to make the change and add tests (the change is trivial, just change `onRequest` to `preValidation` when adding the hook. I figured I'd leave this in case anyone comes across the same issue in the mean time.
